# Generated by Django 3.0.3 on 2020-02-15 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Unreleased', max_length=30)),
                ('genre', models.CharField(max_length=20)),
                ('air_till', models.DateField()),
                ('rating', models.FloatField()),
                ('starring', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='theatre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theatre_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
            ],
        ),
    ]
