# Generated by Django 3.0.5 on 2020-05-01 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Unreleased', max_length=30, verbose_name='Title')),
                ('slug_title', models.SlugField(max_length=30, verbose_name='Url Slug')),
                ('genre', models.CharField(max_length=20, verbose_name='Genre')),
                ('air_till', models.DateField(verbose_name='Showing till')),
                ('rating', models.FloatField(verbose_name='Rating')),
                ('starring', models.TextField(max_length=300, verbose_name='Starring')),
                ('poster', models.ImageField(blank=True, upload_to='poster', verbose_name='Poster')),
                ('blurb', models.TextField(max_length=300, verbose_name='Summary')),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cine_no', models.CharField(max_length=5, verbose_name='Cinema Hall')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showing_at', to='theater.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='Times',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(choices=[('1100', '1100'), ('1400', '1400'), ('1700', '1700'), ('2000', '2000')], max_length=10, verbose_name='Screening time')),
                ('capacity', models.IntegerField(default=9999, verbose_name='Seats left')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theater.Show')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats', models.IntegerField(default=1)),
                ('date', models.DateField(verbose_name='Date')),
                ('time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='theater.Times')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Theatre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theatre_name', models.CharField(max_length=30, verbose_name='Theatre')),
                ('slug_name', models.SlugField(max_length=30, verbose_name='Url Slug')),
                ('address', models.CharField(max_length=30, verbose_name='Address')),
                ('capacity', models.IntegerField(verbose_name='Max Seating')),
                ('city', models.CharField(max_length=30, verbose_name='City')),
                ('state', models.CharField(max_length=30, verbose_name='State')),
                ('showing', models.ManyToManyField(related_name='now_showing', through='theater.Show', to='theater.Movie')),
            ],
        ),
        migrations.AddField(
            model_name='show',
            name='theatre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='now_showing', to='theater.Theatre'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('designation', models.CharField(choices=[('Manager', 'Manager'), ('Desk Clerk', 'Desk Clerk'), ('IT Support', 'IT Support')], default='User', max_length=20, verbose_name='Designation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='show',
            field=models.ManyToManyField(related_name='showing_at', through='theater.Show', to='theater.Theatre'),
        ),
        migrations.AddConstraint(
            model_name='times',
            constraint=models.UniqueConstraint(fields=('time', 'show'), name='Unique timing for show'),
        ),
        migrations.AddConstraint(
            model_name='show',
            constraint=models.UniqueConstraint(fields=('theatre', 'movie'), name='Only one show for a pair of theatre and movie'),
        ),
    ]
