# Generated by Django 3.0.5 on 2020-04-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='designation',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Desk Clerk', 'Desk Clerk'), ('IT Support', 'IT Support')], default='User', max_length=20),
        ),
    ]
