# Generated by Django 3.0.3 on 2020-02-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='currentlyshowing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('capacity', models.IntegerField()),
                ('cine_no', models.IntegerField()),
            ],
        ),
    ]
