# Generated by Django 3.0.5 on 2020-04-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0002_auto_20200427_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, upload_to='poster', verbose_name='Poster'),
        ),
        migrations.AlterField(
            model_name='currentlyshowing',
            name='capacity',
            field=models.IntegerField(verbose_name='Seats left'),
        ),
        migrations.AlterField(
            model_name='currentlyshowing',
            name='cine_no',
            field=models.IntegerField(verbose_name='Cinema Number'),
        ),
        migrations.AlterField(
            model_name='currentlyshowing',
            name='time',
            field=models.TimeField(verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='air_till',
            field=models.DateField(verbose_name='Showing till'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(max_length=20, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.FloatField(verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='starring',
            field=models.TextField(max_length=300, verbose_name='Starring'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(default='Unreleased', max_length=30, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='designation',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Desk Clerk', 'Desk Clerk'), ('IT Support', 'IT Support')], default='User', max_length=20, verbose_name='Designation'),
        ),
        migrations.AlterField(
            model_name='theatre',
            name='address',
            field=models.CharField(max_length=30, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='theatre',
            name='city',
            field=models.CharField(max_length=30, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='theatre',
            name='state',
            field=models.CharField(max_length=30, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='theatre',
            name='theatre_name',
            field=models.CharField(max_length=30, verbose_name='Theatre'),
        ),
    ]
