# Generated by Django 3.0.5 on 2020-04-28 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0003_auto_20200427_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentlyshowing',
            name='movie',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='theater.Movie'),
        ),
        migrations.AlterField(
            model_name='currentlyshowing',
            name='theatre',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='theater.Theatre'),
        ),
    ]
