# Generated by Django 3.0.5 on 2020-04-28 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0004_auto_20200428_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='theatre',
            name='capacity',
            field=models.IntegerField(default=0, verbose_name='Max Seating'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='currentlyshowing',
            name='movie',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='theater.Movie'),
        ),
        migrations.AlterField(
            model_name='currentlyshowing',
            name='theatre',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='theater.Theatre'),
        ),
    ]
