# Generated by Django 3.0.5 on 2020-04-28 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0006_auto_20200428_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='currentlyshowing',
            new_name='Shows',
        ),
        migrations.AlterField(
            model_name='shows',
            name='movie',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='theater.Movie'),
        ),
        migrations.AlterField(
            model_name='shows',
            name='theatre',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='theater.Theatre'),
        ),
    ]
