# Generated by Django 3.0.5 on 2020-04-28 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('theater', '0007_auto_20200428_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='Duration')),
                ('capacity', models.IntegerField(verbose_name='Seats left')),
                ('cine_no', models.IntegerField(verbose_name='Cinema Hall')),
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='theater.Movie')),
                ('theatre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='theater.Theatre')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='seats',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Shows',
        ),
        migrations.AddField(
            model_name='transaction',
            name='show',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='theater.Show'),
        ),
    ]
