# Generated by Django 3.0.5 on 2020-04-29 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0010_auto_20200429_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='blurb',
            field=models.TextField(default='Hello', max_length=300, verbose_name='Summary'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='show',
            name='movie',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='theater.Movie'),
        ),
        migrations.AlterField(
            model_name='show',
            name='theatre',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='theater.Theatre'),
        ),
    ]
